dist: bionic
matrix:
  include:
    - language: csharp
      solution: Condensate_API.sln
      mono: none
      dotnet: 2.2.104
      script: dotnet build ./Condensate_API/Condensate_API.csproj
      # jobs:
      #   include:
      #   - stage: build
      
        # - stage: test
        #   script: dotnet test ./XUnitTests/XUnitTests.csproj
    # - language: node_js
    #   node_js: "9"
    #   before_install: cd AngularApp
    # - install: npm install
    #   script: ng build
      
    
