dist: bionic
services:
  - docker
language: csharp
solution: Condensate_API.sln
mono: none
dotnet: 2.2.104
jobs:
  include:
    - stage: build
      script: 
        - dotnet restore
        - dotnet build ./Condensate_API/Condensate_API.csproj
    
    - stage: test
      script: dotnet test ./XUnitTests/XUnitTests.csproj
    
    - stage: publish
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        - dotnet publish -c Release ./Condensate_API/Condensate_API.csproj
        - docker build --tag jukebox1412/condensate:1.0 ./Condensate_API/
        - docker push jukebox1412/condensate