matrix:
  include:
    - dist: bionic
      language: csharp
      solution: Condensate_API.sln
      mono: none
      dotnet: 2.2.104
      jobs:
        include:
        - stage: build
          script: dotnet build ./Condensate_API/Condensate_API.csproj
      
        - stage: test
          script: dotnet test ./XUnitTests/XUnitTests.csproj
          
    - language: node_js
      node_js: "9"
      before_install: cd ./AngularApp
    - install: npm install
      jobs:
        include:
        - stage: build
          script: ng build
    
