services:
  - docker
language: csharp
mono: none
solution: Condensate_API.sln
os: linux
dotnet: 2.2.104
jobs:
  include:
    - stage: build
      script: dotnet build ./Condensate_API/Condensate_API.csproj
    
    - stage: test
      script: dotnet test ./XUnitTests/XUnitTests.csproj
    
    - stage: publish
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        - dotnet publish -c Release ./Condensate_API/Condensate_API.csproj
        - docker build --tag jukebox1412/condensate:1.1.$TRAVIS_BUILD_NUMBER ./Condensate_API/
        # also push this as latest
        - docker build --tag jukebox1412/condensate:latest ./Condensate_API/
        - docker push jukebox1412/condensate