dist: bionic
# do this 'matrix' thing instead of 'jobs: include:' cause we need multiple languages in one repo!
matrix:
  include:
    - name: "ASP.Net Core API"
      language: csharp
      solution: Condensate_API.sln
      mono: none
      dotnet: 2.2.104
      script: 
        - dotnet build ./Condensate_API/Condensate_API.csproj
        - dotnet test ./XUnitTests/XUnitTests.csproj

    - name: "Angular Client App"
      language: node_js
      node_js: "10.16.0"
      before_install: cd AngularApp
      install: npm install
      script: ng build